/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PageStatusBarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  renderMode: "post-processor",
  triggerOnAnyType: false,
  includeFolders: [],
  excludeFolders: [],
  hideNativeProperties: true,
  sections: {
    header: true,
    properties: true,
    navigation: true,
    children: true,
    files: true,
    usedBy: true
  },
  enabledExtensions: {
    Project: true,
    Ongoing: true
  },
  deferToLegacyStub: true
};

// src/render.ts
var import_obsidian3 = require("obsidian");

// src/util.ts
var import_obsidian = require("obsidian");
function basenameOf(path) {
  const last = path.split("/").pop() ?? path;
  return last.replace(/\.md$/i, "");
}
function parseWikilink(raw) {
  const inner = raw.trim().replace(/^\[\[|\]\]$/g, "");
  const [target, alias] = inner.split("|");
  return { target: target.trim(), alias: alias?.trim() };
}
function cap(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
function resolveLink(app, source, ref) {
  if (ref == null || ref === "")
    return null;
  if (typeof ref === "object" && ref !== null) {
    const r = ref;
    if (r.path) {
      const f = app.vault.getAbstractFileByPath(r.path);
      if (f instanceof import_obsidian.TFile)
        return f;
      return { missingName: basenameOf(r.path) };
    }
    if (r.link) {
      const { target } = parseWikilink(`[[${r.link}]]`);
      const f = app.metadataCache.getFirstLinkpathDest(target, source.path);
      return f ?? { missingName: basenameOf(target) };
    }
    return null;
  }
  if (typeof ref === "string") {
    const trimmed = ref.trim();
    if (!trimmed)
      return null;
    const { target } = parseWikilink(trimmed);
    const f = app.metadataCache.getFirstLinkpathDest(target, source.path);
    return f ?? { missingName: basenameOf(target) };
  }
  return null;
}
function asArray(v) {
  if (v == null)
    return [];
  return Array.isArray(v) ? v : [v];
}
function fmtScalar(v) {
  if (v == null || v === "")
    return "";
  if (Array.isArray(v)) {
    return v.map(fmtScalar).filter(Boolean).join(", ");
  }
  if (typeof v === "object" && v !== null) {
    const r = v;
    if (r.path) {
      const base = basenameOf(r.path);
      return `[[${r.path.replace(/\.md$/i, "")}|${base}]]`;
    }
    if (r.link)
      return `[[${r.link}]]`;
    if (v instanceof Date)
      return v.toISOString().slice(0, 10);
    return String(v);
  }
  return String(v);
}

// src/type-index.ts
var import_obsidian2 = require("obsidian");
var TypeIndex = class {
  constructor(app) {
    this.app = app;
    this.byPath = /* @__PURE__ */ new Map();
    this.pathsByKey = /* @__PURE__ */ new Map();
    this.listeners = /* @__PURE__ */ new Set();
    this._ready = false;
    this.rebuildScheduled = false;
  }
  isReady() {
    return this._ready;
  }
  onChange(fn) {
    this.listeners.add(fn);
    return () => this.listeners.delete(fn);
  }
  scheduleInitialBuild() {
    if (this.rebuildScheduled || this._ready)
      return;
    this.scheduleRebuild();
  }
  scheduleRebuild() {
    if (this.rebuildScheduled)
      return;
    this.rebuildScheduled = true;
    const run = () => {
      try {
        this.rebuild();
      } finally {
        this.rebuildScheduled = false;
      }
    };
    const w = window;
    if (typeof w.requestIdleCallback === "function") {
      w.requestIdleCallback(run);
    } else {
      run();
    }
  }
  rebuild() {
    this.byPath.clear();
    this.pathsByKey.clear();
    for (const file of this.app.vault.getMarkdownFiles()) {
      this.indexFile(file);
    }
    this._ready = true;
    this.notify();
  }
  updateFile(file) {
    const before = this.byPath.has(file.path);
    this.removeFile(file.path);
    this.indexFile(file);
    const after = this.byPath.has(file.path);
    if (this._ready && (before || after))
      this.notify();
  }
  handleRename(file, oldPath) {
    this.removeFile(oldPath);
    this.indexFile(file);
    if (this._ready)
      this.notify();
  }
  removeFile(path) {
    const known = this.byPath.get(path);
    if (!known)
      return;
    this.byPath.delete(path);
    for (const [key, paths] of this.pathsByKey) {
      paths.delete(path);
      if (paths.size === 0)
        this.pathsByKey.delete(key);
    }
  }
  knownTypeForFile(file) {
    return this.byPath.get(file.path) ?? null;
  }
  hasKnownType(file, fm) {
    return this.resolveTypesForFrontmatter(file, fm).length > 0;
  }
  resolveTypesForFrontmatter(source, fm) {
    const out = [];
    for (const ref of typeRefs(fm)) {
      const cls = this.resolveClassRef(source, ref);
      if (cls && !out.includes(cls))
        out.push(cls);
    }
    return out;
  }
  resolveClassRef(source, ref) {
    if (ref == null || ref === "")
      return null;
    const resolved = resolveLink(this.app, source, ref);
    if (resolved instanceof import_obsidian2.TFile && this.byPath.has(resolved.path)) {
      return resolved;
    }
    const key = keyFromRef(ref);
    if (!key)
      return null;
    const direct = this.app.metadataCache.getFirstLinkpathDest(key, source.path);
    if (direct && this.byPath.has(direct.path))
      return direct;
    const paths = this.pathsByKey.get(normalizeKey(key));
    if (!paths || paths.size === 0)
      return null;
    const candidates = Array.from(paths).map((path) => this.byPath.get(path)).filter((x) => !!x);
    if (candidates.length === 1)
      return candidates[0].file;
    const schemaClasses = candidates.filter((known) => {
      const t = known.frontmatter["type"] ?? known.frontmatter["Type"];
      return t == null || t === "" || typeRefs({ type: t }).includes("Class");
    });
    if (schemaClasses.length === 1)
      return schemaClasses[0].file;
    return candidates.slice().sort((a, b) => a.file.path.localeCompare(b.file.path))[0]?.file ?? null;
  }
  classLineage(types) {
    const levels = [];
    let current = uniqueFiles(types);
    const visited = /* @__PURE__ */ new Set();
    while (current.length) {
      levels.push(current);
      const next = [];
      for (const file of current) {
        visited.add(file.path);
        for (const parent of this.parentsOf(file)) {
          if (visited.has(parent.path))
            continue;
          if (!next.includes(parent))
            next.push(parent);
        }
      }
      current = next;
    }
    return levels;
  }
  parentsOf(file) {
    const known = this.byPath.get(file.path);
    if (!known)
      return [];
    const out = [];
    for (const ref of known.parentRefs) {
      const parent = this.resolveClassRef(file, ref);
      if (parent && !out.includes(parent))
        out.push(parent);
    }
    return out;
  }
  indexFile(file) {
    const fm = this.app.metadataCache.getFileCache(file)?.frontmatter ?? {};
    if (!isClassDefinition(fm))
      return;
    const parentRefs = asArray(fm["subClassOf"] ?? fm["SubClassOf"]);
    this.byPath.set(file.path, { file, frontmatter: fm, parentRefs });
    this.addKey(file.path, file.basename);
    if (typeof fm["name"] === "string")
      this.addKey(file.path, fm["name"]);
    const pathNoExt = file.path.replace(/\.md$/i, "");
    const segments = pathNoExt.split("/");
    for (let i = 0; i < segments.length; i++) {
      this.addKey(file.path, segments.slice(i).join("/"));
    }
  }
  addKey(path, raw) {
    const key = normalizeKey(raw);
    if (!key)
      return;
    let paths = this.pathsByKey.get(key);
    if (!paths) {
      paths = /* @__PURE__ */ new Set();
      this.pathsByKey.set(key, paths);
    }
    paths.add(path);
  }
  notify() {
    for (const fn of this.listeners)
      fn();
  }
};
function typeRefs(fm) {
  const raw = fm["type"] ?? fm["Type"];
  const out = [];
  for (const item of asArray(raw)) {
    if (typeof item === "string") {
      const parts = item.includes(",") ? item.split(",") : [item];
      for (const part of parts) {
        const trimmed = part.trim();
        if (trimmed)
          out.push(trimmed);
      }
    } else if (item && typeof item === "object") {
      const r = item;
      if (r.path)
        out.push(r.path);
      if (r.link)
        out.push(r.link);
    }
  }
  return out;
}
function isClassDefinition(fm) {
  const t = fm["type"] ?? fm["Type"];
  if (typeRefs({ type: t }).includes("Class"))
    return true;
  if (Array.isArray(fm["fieldsOrder"]))
    return true;
  if (Object.prototype.hasOwnProperty.call(fm, "subClassOf"))
    return true;
  if (Object.prototype.hasOwnProperty.call(fm, "extends"))
    return true;
  return false;
}
function keyFromRef(ref) {
  if (typeof ref === "string")
    return parseWikilink(ref).target;
  if (ref && typeof ref === "object") {
    const r = ref;
    if (r.path)
      return r.path.replace(/\.md$/i, "");
    if (r.link)
      return parseWikilink(r.link).target;
  }
  return "";
}
function normalizeKey(raw) {
  return raw.trim().replace(/\.md$/i, "").toLowerCase();
}
function uniqueFiles(files) {
  const out = [];
  for (const file of files) {
    if (!out.includes(file))
      out.push(file);
  }
  return out;
}

// src/render.ts
var SKIP_PROPS_CC = [
  "type",
  "mapWithTag",
  "tagNames",
  "filesPaths",
  "bookmarksGroups",
  "excludes",
  "savedViews",
  "favoriteView",
  "fields",
  "fieldsOrder",
  "columns",
  "limit",
  "version",
  "icon",
  "statusbar",
  "statusBar"
];
var SKIP_PROPS = new Set(SKIP_PROPS_CC.map((s) => s.toLowerCase()));
var NAV_FIELDS = [
  ["parentProject", "Up"],
  ["up", "Up"],
  ["broader", "Broader"],
  ["subClassOf", "Parent"],
  ["extends", "Extends"],
  ["inScheme", "In scheme"],
  ["prev", "Prev"],
  ["next", "Next"],
  ["sameAs", "Same as"],
  ["replacedBy", "Replaced by"]
];
var NAV_KEYS = new Set(NAV_FIELDS.map(([k]) => k.toLowerCase()));
var CHILD_FIELDS = [
  ["parentProject", "Sub-projects"],
  ["up", "Children"],
  ["broader", "Narrower"],
  ["subClassOf", "Subclasses"],
  ["extends", "Subclasses (UI)"],
  ["type", "Instances"],
  ["inScheme", "Members"],
  ["sameAs", "Aliases"]
];
function getFrontmatter(app, file) {
  const cache = app.metadataCache.getFileCache(file);
  return cache?.frontmatter ?? {};
}
function optsFromSettings(s) {
  return {
    showHeader: s.sections.header,
    showProperties: s.sections.properties,
    showNavigation: s.sections.navigation,
    showChildren: s.sections.children,
    showFiles: s.sections.files,
    showUsedBy: s.sections.usedBy
  };
}
async function renderStatusBar(container, ctx, component, extensions) {
  container.empty();
  container.addClass("psb-root");
  const { app, file, frontmatter: fm, settings } = ctx;
  const opts = optsFromSettings(settings);
  const sourcePath = file.path;
  const currentKnownType = ctx.typeIndex.knownTypeForFile(file);
  const typeFiles = ctx.typeIndex.resolveTypesForFrontmatter(file, fm);
  if (currentKnownType && !typeFiles.includes(currentKnownType.file)) {
    typeFiles.unshift(currentKnownType.file);
  }
  const lineage = ctx.typeIndex.classLineage(typeFiles);
  const isClassDef = Object.prototype.hasOwnProperty.call(fm, "subClassOf") || Object.prototype.hasOwnProperty.call(fm, "extends");
  const rawTypes = typeRefs(fm);
  if (opts.showHeader && (lineage.length || rawTypes.length)) {
    const chip = container.createDiv({ cls: "psb-section psb-type-chip" });
    chip.createSpan({ cls: "psb-label", text: "Type: " });
    await renderInline(
      app,
      chip,
      lineage.length ? lineage.map((level) => level.map((cls) => linkForFile(cls)).join(", ")).join(" -> ") : rawTypes.map((ref) => linkForTypeRef(app, file, ref)).join(", "),
      sourcePath,
      component
    );
  }
  if (opts.showProperties) {
    const ordered = [];
    if (!isClassDef) {
      const classes = typeFiles;
      for (const cls of classes) {
        const clsFm = getFrontmatter(app, cls);
        const fieldsOrder = clsFm?.["fieldsOrder"];
        if (Array.isArray(fieldsOrder)) {
          for (const f of fieldsOrder)
            ordered.push([String(f), cap(String(f))]);
        }
      }
    }
    const seen = new Set(ordered.map(([k]) => k.toLowerCase()));
    for (const key of Object.keys(fm)) {
      const lk = key.toLowerCase();
      if (seen.has(lk))
        continue;
      if (opts.showNavigation && NAV_KEYS.has(lk))
        continue;
      ordered.push([key, cap(key)]);
      seen.add(lk);
    }
    const fields = [];
    for (const [key, label] of ordered) {
      if (SKIP_PROPS.has(key.toLowerCase()))
        continue;
      const v = fm[key];
      const s = fmtFieldValue(app, file, key, v, ctx);
      if (!s)
        continue;
      fields.push([label, s]);
    }
    if (fields.length) {
      const sec = container.createDiv({ cls: "psb-section psb-properties" });
      sec.createEl("h4", { text: "Metadata" });
      const grid = sec.createDiv({ cls: "psb-field-grid" });
      for (const [label, md] of fields) {
        const item = grid.createDiv({ cls: "psb-field" });
        item.createDiv({ cls: "psb-field-label", text: label });
        const value = item.createDiv({ cls: "psb-field-value" });
        await renderInline(app, value, md, sourcePath, component);
      }
    }
  }
  if (opts.showNavigation) {
    const rows = navigationRows(app, file, fm, ctx);
    if (rows.length) {
      const sec = container.createDiv({ cls: "psb-section psb-navigation" });
      sec.createEl("h4", { text: "Navigation" });
      const body = sec.createDiv({ cls: "psb-nav-lines" });
      for (const row of rows) {
        const line = body.createDiv({ cls: "psb-nav-line" });
        for (let i = 0; i < row.length; i++) {
          if (i > 0)
            line.createSpan({ cls: "psb-nav-separator", text: " \xB7 " });
          line.createSpan({ cls: "psb-nav-label", text: `${row[i].label}: ` });
          const value = line.createSpan({ cls: "psb-nav-value" });
          await renderInline(app, value, row[i].value, sourcePath, component);
        }
      }
    }
  }
  if (opts.showChildren && ctx.linkIndex.isReady()) {
    const grouped = groupIncomingByField(app, file, ctx);
    const childGroups = [];
    for (const [field, label] of CHILD_FIELDS) {
      const kids = grouped.get(field);
      if (kids && kids.length)
        childGroups.push({ label, pages: kids });
    }
    if (childGroups.length) {
      const sec = container.createDiv({ cls: "psb-section psb-children" });
      sec.createEl("h4", { text: "Children" });
      for (const { label, pages } of childGroups) {
        const grp = sec.createDiv({ cls: "psb-children-group" });
        grp.createEl("h5", { text: `${label} (${pages.length})` });
        await renderTable(
          app,
          grp,
          ["Item", "Type", "Status"],
          pages.map((p) => [
            `[[${p.path.replace(/\.md$/i, "")}|${p.basename}]]`,
            String(getFrontmatter(app, p)["type"] ?? ""),
            String(getFrontmatter(app, p)["status"] ?? "")
          ]),
          sourcePath,
          component
        );
      }
    }
  }
  if (opts.showFiles) {
    const folderHere = file.parent?.path ?? "";
    const filesFolder = folderHere ? `${folderHere}/${file.basename}` : file.basename;
    const files = app.vault.getMarkdownFiles().filter((p) => p.path !== file.path && (p.parent?.path ?? "") === filesFolder).sort((a, b) => a.basename.localeCompare(b.basename));
    if (files.length) {
      const sec = container.createDiv({ cls: "psb-section psb-files" });
      sec.createEl("h4", { text: `Files (${files.length})` });
      await renderTable(
        app,
        sec,
        ["File", "Type", "Updated"],
        files.map((p) => [
          `[[${p.path.replace(/\.md$/i, "")}|${p.basename}]]`,
          String(getFrontmatter(app, p)["type"] ?? ""),
          new Date(p.stat.mtime).toISOString().slice(0, 10)
        ]),
        sourcePath,
        component
      );
      sec.createEl("div", {
        cls: "psb-meta",
        text: `Folder: ${filesFolder}/`
      });
    }
  }
  if (opts.showUsedBy && ctx.linkIndex.isReady()) {
    const childKeys = new Set(CHILD_FIELDS.map(([k]) => k));
    const incoming = collectIncoming(app, file, ctx).filter(
      (m) => m.fields.some((f) => !childKeys.has(f))
    );
    if (incoming.length) {
      const sec = container.createDiv({ cls: "psb-section psb-used-by" });
      sec.createEl("h4", { text: `Used by (${incoming.length})` });
      await renderTable(
        app,
        sec,
        ["Item", "Type", "Status", "Field"],
        incoming.map(({ file: p, fields }) => [
          `[[${p.path.replace(/\.md$/i, "")}|${p.basename}]]`,
          String(getFrontmatter(app, p)["type"] ?? ""),
          String(getFrontmatter(app, p)["status"] ?? ""),
          fields.filter((f) => !childKeys.has(f)).join(", ")
        ]),
        sourcePath,
        component
      );
    }
  }
  const extensionTypes = new Set(typeRefs(fm));
  if (extensionTypes.size) {
    for (const ext of extensions) {
      if (!extensionTypes.has(ext.type))
        continue;
      const enabled = ctx.settings.enabledExtensions[ext.type] !== false;
      if (!enabled)
        continue;
      const extEl = container.createDiv({
        cls: `psb-section psb-extension psb-ext-${ext.type.toLowerCase()}`
      });
      try {
        await ext.render(extEl, ctx);
      } catch (e) {
        console.error(`[page-status-bar] extension ${ext.type} failed:`, e);
      }
    }
  }
}
function linkForFile(file) {
  return `[[${file.path.replace(/\.md$/i, "")}|${file.basename}]]`;
}
function linkForTypeRef(app, source, ref) {
  const resolved = resolveLink(app, source, ref);
  if (resolved instanceof import_obsidian3.TFile)
    return linkForFile(resolved);
  if (typeof ref === "string")
    return ref;
  return fmtScalar(ref);
}
function navigationRows(app, source, fm, ctx) {
  const renderField = (field) => {
    const value = frontmatterValue(fm, field);
    if (value == null || value === "")
      return "";
    const list = Array.isArray(value) ? value : [value];
    return list.map((item) => fmtFieldValue(app, source, field, item, ctx)).filter(Boolean).join(", ");
  };
  const rowFrom = (parts) => parts.filter((part) => part.value);
  return [
    rowFrom([
      { label: "Up", value: renderField("parentProject") },
      { label: "Up", value: renderField("up") },
      { label: "Parent", value: renderField("subClassOf") },
      { label: "Extends", value: renderField("extends") },
      { label: "Broader", value: renderField("broader") },
      { label: "In scheme", value: renderField("inScheme") }
    ]),
    rowFrom([
      { label: "Prev", value: renderField("prev") },
      { label: "Next", value: renderField("next") }
    ]),
    rowFrom([{ label: "Same as", value: renderField("sameAs") }]),
    rowFrom([{ label: "Replaced by", value: renderField("replacedBy") }])
  ].filter((row) => row.length);
}
function frontmatterValue(fm, key) {
  if (Object.prototype.hasOwnProperty.call(fm, key))
    return fm[key];
  const found = Object.keys(fm).find((k) => k.toLowerCase() === key.toLowerCase());
  return found ? fm[found] : void 0;
}
function fmtFieldValue(app, source, key, value, ctx) {
  if (value == null || value === "")
    return "";
  if (key.toLowerCase() === "type") {
    const resolved = ctx.typeIndex.resolveTypesForFrontmatter(source, { type: value }).map((file) => linkForFile(file)).join(", ");
    return resolved || linkForTypeRef(app, source, value);
  }
  if (Array.isArray(value)) {
    return value.map((item) => fmtFieldValue(app, source, key, item, ctx)).filter(Boolean).join(", ");
  }
  if (typeof value === "object" && value !== null) {
    const resolved = resolveLink(app, source, value);
    if (resolved instanceof import_obsidian3.TFile)
      return linkForFile(resolved);
    const r = value;
    if (r.path || r.link)
      return fmtScalar(value);
    if (value instanceof Date)
      return value.toISOString().slice(0, 10);
    return String(value);
  }
  if (typeof value === "string") {
    const trimmed = value.trim();
    if (!trimmed)
      return "";
    const resolved = resolveLink(app, source, trimmed);
    if (resolved instanceof import_obsidian3.TFile)
      return linkForFile(resolved);
  }
  return fmtScalar(value);
}
async function renderInline(app, el, md, sourcePath, component) {
  const re = /\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g;
  let last = 0;
  for (const match of md.matchAll(re)) {
    const index = match.index ?? 0;
    if (index > last) {
      el.appendText(md.slice(last, index));
    }
    const target = match[1].trim();
    const label = (match[2] ?? basenameOf(target)).trim();
    const link = el.createEl("a", {
      cls: "internal-link",
      text: label,
      attr: {
        "data-href": target,
        href: target,
        target: "_blank",
        rel: "noopener nofollow"
      }
    });
    link.setAttr("aria-label", target);
    last = index + match[0].length;
  }
  if (last < md.length) {
    el.appendText(md.slice(last));
  }
}
async function renderTable(app, el, headers, rows, sourcePath, component) {
  const table = el.createEl("table", { cls: "psb-table" });
  const thead = table.createEl("thead");
  const headerRow = thead.createEl("tr");
  for (const h of headers)
    headerRow.createEl("th", { text: h });
  const tbody = table.createEl("tbody");
  for (const row of rows) {
    const tr = tbody.createEl("tr");
    for (const cell of row) {
      const td = tr.createEl("td");
      if (cell)
        await renderInline(app, td, cell, sourcePath, component);
    }
  }
}
function groupIncomingByField(app, target, ctx) {
  const out = /* @__PURE__ */ new Map();
  for (const e of ctx.linkIndex.incomingFor(target.path)) {
    if (e.sourcePath === target.path)
      continue;
    const af = app.vault.getAbstractFileByPath(e.sourcePath);
    if (!(af instanceof import_obsidian3.TFile))
      continue;
    let list = out.get(e.field);
    if (!list) {
      list = [];
      out.set(e.field, list);
    }
    if (!list.includes(af))
      list.push(af);
  }
  for (const list of out.values()) {
    list.sort((a, b) => a.basename.localeCompare(b.basename));
  }
  return out;
}
function collectIncoming(app, target, ctx) {
  const byPath = /* @__PURE__ */ new Map();
  for (const e of ctx.linkIndex.incomingFor(target.path)) {
    if (e.sourcePath === target.path)
      continue;
    let set = byPath.get(e.sourcePath);
    if (!set) {
      set = /* @__PURE__ */ new Set();
      byPath.set(e.sourcePath, set);
    }
    set.add(e.field);
  }
  const out = [];
  for (const [path, fields] of byPath) {
    const af = app.vault.getAbstractFileByPath(path);
    if (!(af instanceof import_obsidian3.TFile))
      continue;
    out.push({ file: af, fields: Array.from(fields) });
  }
  out.sort((a, b) => a.file.basename.localeCompare(b.file.basename));
  return out;
}

// src/trigger.ts
function shouldRenderFor(file, fm, settings, typeIndex) {
  const optOut = fm["statusBar"] ?? fm["statusbar"];
  if (optOut === false)
    return false;
  const folder = file.parent?.path ?? "";
  if (settings.includeFolders.length) {
    const ok = settings.includeFolders.some((p) => withinFolder(folder, p));
    if (!ok)
      return false;
  }
  for (const p of settings.excludeFolders) {
    if (withinFolder(folder, p))
      return false;
  }
  if (settings.triggerOnAnyType) {
    if (!isClassDefinition(fm) && typeRefs(fm).length === 0) {
      return false;
    }
  }
  return true;
}
function withinFolder(folder, prefix) {
  const p = prefix.replace(/^\/|\/$/g, "");
  if (!p)
    return true;
  return folder === p || folder.startsWith(p + "/");
}

// src/settings.ts
var import_obsidian4 = require("obsidian");
var PageStatusBarSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const s = this.plugin.settings;
    new import_obsidian4.Setting(containerEl).setName("Rendering").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Render mode").setDesc(
      "Where to render the status bar. Reading view = markdown post-processor; Edit modes = CodeMirror widget; Both = everywhere."
    ).addDropdown(
      (d) => d.addOption("post-processor", "Reading view only").addOption("view-extension", "Edit modes only").addOption("both", "Both").setValue(s.renderMode).onChange(async (v) => {
        s.renderMode = v;
        await this.plugin.saveSettings();
        this.plugin.refreshAll();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Render only on pages with a known type:").setDesc(
      "When on, only pages whose frontmatter `type:` resolves to a class/type page get the metadata bar. `subClassOf:` is used for the displayed type chain."
    ).addToggle(
      (t) => t.setValue(s.triggerOnAnyType).onChange(async (v) => {
        s.triggerOnAnyType = v;
        await this.plugin.saveSettings();
        this.plugin.refreshAll();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Defer to legacy dataview stub").setDesc(
      'When on, the plugin skips rendering on pages that still contain a `dv.view("{internals}/Classes/_views/any")` codeblock \u2014 so the old and new renderers don\'t both fire during migration.'
    ).addToggle(
      (t) => t.setValue(s.deferToLegacyStub).onChange(async (v) => {
        s.deferToLegacyStub = v;
        await this.plugin.saveSettings();
        this.plugin.refreshAll();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Hide native frontmatter properties").setDesc(
      "Hide Obsidian's built-in properties block. The status bar renders properties itself; native UI is redundant when the plugin is on."
    ).addToggle(
      (t) => t.setValue(s.hideNativeProperties).onChange(async (v) => {
        s.hideNativeProperties = v;
        await this.plugin.saveSettings();
        this.plugin.applyBodyClasses();
        this.plugin.refreshAll();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Folders").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Include folders").setDesc(
      "One folder path per line. If non-empty, the status bar renders ONLY in these folders (and their descendants). Empty = no restriction."
    ).addTextArea((t) => {
      t.inputEl.rows = 4;
      t.inputEl.style.width = "100%";
      t.setValue(s.includeFolders.join("\n")).onChange(async (v) => {
        s.includeFolders = v.split("\n").map((x) => x.trim()).filter(Boolean);
        await this.plugin.saveSettings();
        this.plugin.refreshAll();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Exclude folders").setDesc(
      "One folder path per line. The status bar will NOT render in these folders (and their descendants)."
    ).addTextArea((t) => {
      t.inputEl.rows = 4;
      t.inputEl.style.width = "100%";
      t.setValue(s.excludeFolders.join("\n")).onChange(async (v) => {
        s.excludeFolders = v.split("\n").map((x) => x.trim()).filter(Boolean);
        await this.plugin.saveSettings();
        this.plugin.refreshAll();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Sections").setHeading();
    const sectionToggle = (key, label) => {
      new import_obsidian4.Setting(containerEl).setName(label).addToggle(
        (t) => t.setValue(s.sections[key]).onChange(async (v) => {
          s.sections[key] = v;
          await this.plugin.saveSettings();
          this.plugin.refreshAll();
        })
      );
    };
    sectionToggle("header", "Type chain");
    sectionToggle("properties", "Metadata fields");
    sectionToggle("navigation", "Navigation");
    sectionToggle("children", "Children");
    sectionToggle("files", "Files");
    sectionToggle("usedBy", "Used by");
    new import_obsidian4.Setting(containerEl).setName("Type extensions").setHeading();
    const types = /* @__PURE__ */ new Set([
      ...this.plugin.extensions.map((e) => e.type),
      ...Object.keys(s.enabledExtensions)
    ]);
    for (const type of Array.from(types).sort()) {
      new import_obsidian4.Setting(containerEl).setName(type).setDesc(`Render type-specific extras below the universal sections for \`type: ${type}\`.`).addToggle(
        (t) => t.setValue(s.enabledExtensions[type] !== false).onChange(async (v) => {
          s.enabledExtensions[type] = v;
          await this.plugin.saveSettings();
          this.plugin.refreshAll();
        })
      );
    }
  }
};

// src/extensions/project.ts
var import_obsidian5 = require("obsidian");
async function renderMd(el, md, ctx, component) {
  await import_obsidian5.MarkdownRenderer.render(ctx.app, md, el, ctx.file.path, component);
}
function makeProjectExtension(typeName) {
  return {
    type: typeName,
    async render(container, ctx) {
      const fm = ctx.frontmatter;
      const component = new import_obsidian5.Component();
      component.load();
      try {
        const phases = fm["phases"];
        if (Array.isArray(phases) && phases.length) {
          const sec = container.createDiv({
            cls: "psb-section psb-ext-phases"
          });
          sec.createEl("h4", { text: `Phases (${phases.length})` });
          if (typeof phases[0] === "object" && phases[0] !== null) {
            const keySet = /* @__PURE__ */ new Set();
            for (const ph of phases) {
              if (ph && typeof ph === "object") {
                for (const k of Object.keys(ph)) {
                  keySet.add(k);
                }
              }
            }
            const keys = Array.from(keySet);
            const table = sec.createEl("table", { cls: "psb-table" });
            const headerRow = table.createEl("thead").createEl("tr");
            for (const k of keys)
              headerRow.createEl("th", { text: cap(k) });
            const tbody = table.createEl("tbody");
            for (const ph of phases) {
              const tr = tbody.createEl("tr");
              for (const k of keys) {
                const td = tr.createEl("td");
                const v = ph[k];
                const md = fmtScalar(v);
                if (md)
                  await renderMd(td, md, ctx, component);
              }
            }
          } else {
            const ul = sec.createEl("ul");
            for (const ph of phases) {
              const li = ul.createEl("li");
              const md = fmtScalar(ph);
              if (md)
                await renderMd(li, md, ctx, component);
            }
          }
        }
        const decisions = fm["decisions"];
        if (Array.isArray(decisions) && decisions.length) {
          const sec = container.createDiv({
            cls: "psb-section psb-ext-decisions"
          });
          sec.createEl("h4", { text: `Decisions (${decisions.length})` });
          const ul = sec.createEl("ul");
          for (const d of asArray(decisions)) {
            const li = ul.createEl("li");
            const md = fmtScalar(d);
            if (md)
              await renderMd(li, md, ctx, component);
          }
        }
      } finally {
        component.unload();
      }
    }
  };
}
var projectExtensions = [
  makeProjectExtension("Project"),
  makeProjectExtension("Ongoing")
];

// src/editor-view.ts
var import_view = require("@codemirror/view");
var import_view2 = require("@codemirror/view");
var import_state = require("@codemirror/state");
var import_obsidian6 = require("obsidian");
var bridge = null;
function setEditorViewBridge(ctx) {
  bridge = ctx;
}
function fileForView(app, view) {
  let match = null;
  app.workspace.iterateAllLeaves((leaf) => {
    if (match)
      return;
    const mv = leaf.view;
    if (!(mv instanceof import_obsidian6.MarkdownView))
      return;
    const editor = mv.editor;
    const cm = editor?.cm;
    if (cm === view)
      match = mv.file ?? null;
  });
  return match;
}
var StatusBarWidget = class _StatusBarWidget extends import_view.WidgetType {
  constructor(filePath, version) {
    super();
    this.filePath = filePath;
    this.version = version;
    this.component = null;
  }
  eq(other) {
    return other instanceof _StatusBarWidget && other.filePath === this.filePath && other.version === this.version;
  }
  toDOM() {
    const root = createDiv({ cls: "psb-editor-host" });
    if (!bridge)
      return root;
    const { app, getSettings, getExtensions, getLinkIndex, getTypeIndex } = bridge;
    const af = app.vault.getAbstractFileByPath(this.filePath);
    if (!(af instanceof import_obsidian6.TFile))
      return root;
    const settings = getSettings();
    if (settings.renderMode === "post-processor")
      return root;
    const fm = app.metadataCache.getFileCache(af)?.frontmatter ?? {};
    if (!shouldRenderFor(af, fm, settings, getTypeIndex()))
      return root;
    const component = new import_obsidian6.Component();
    component.load();
    this.component = component;
    const ctx = {
      app,
      file: af,
      frontmatter: fm,
      settings,
      linkIndex: getLinkIndex(),
      typeIndex: getTypeIndex()
    };
    void renderStatusBar(root, ctx, component, getExtensions());
    return root;
  }
  destroy() {
    if (this.component) {
      this.component.unload();
      this.component = null;
    }
  }
  ignoreEvent() {
    return false;
  }
};
var setStatusBarDeco = import_state.StateEffect.define();
var refreshStatusBarDeco = import_state.StateEffect.define();
var statusBarField = import_state.StateField.define({
  create: () => import_view2.Decoration.none,
  update(deco, tr) {
    for (const e of tr.effects) {
      if (e.is(setStatusBarDeco))
        return e.value;
    }
    return deco.map(tr.changes);
  },
  provide: (f) => import_view.EditorView.decorations.from(f)
});
function buildDecoSet(view, version) {
  if (!bridge)
    return import_view2.Decoration.none;
  if (bridge.getSettings().renderMode === "post-processor") {
    return import_view2.Decoration.none;
  }
  const file = fileForView(bridge.app, view);
  if (!file)
    return import_view2.Decoration.none;
  const fm = bridge.app.metadataCache.getFileCache(file)?.frontmatter ?? {};
  if (!shouldRenderFor(file, fm, bridge.getSettings(), bridge.getTypeIndex())) {
    return import_view2.Decoration.none;
  }
  const widget = import_view2.Decoration.widget({
    widget: new StatusBarWidget(file.path, version),
    block: true,
    side: -1
  });
  return import_view2.Decoration.set([widget.range(0)]);
}
var statusBarObserver = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.version = 0;
      this.sync(view);
    }
    update(u) {
      const refreshRequested = u.transactions.some(
        (tr) => tr.effects.some((effect) => effect.is(refreshStatusBarDeco))
      );
      if (u.docChanged || refreshRequested) {
        this.sync(u.view);
      }
    }
    sync(view) {
      this.version++;
      const set = buildDecoSet(view, this.version);
      queueMicrotask(() => {
        view.dispatch({ effects: setStatusBarDeco.of(set) });
      });
    }
  }
);
var statusBarViewExtension = [statusBarField, statusBarObserver];
function refreshAllEditorViews(app) {
  app.workspace.iterateAllLeaves((leaf) => {
    const view = leaf.view;
    if (view instanceof import_obsidian6.MarkdownView) {
      const cm = view.editor?.cm;
      if (cm)
        cm.dispatch({ effects: refreshStatusBarDeco.of(null) });
    }
  });
}

// src/link-index.ts
var import_obsidian7 = require("obsidian");
var LinkIndex = class {
  constructor(app) {
    this.app = app;
    this.incoming = /* @__PURE__ */ new Map();
    this.knownSources = /* @__PURE__ */ new Set();
    this._ready = false;
    this.rebuildScheduled = false;
    this.listeners = /* @__PURE__ */ new Set();
  }
  isReady() {
    return this._ready;
  }
  /** Subscribe to readiness flips and incremental updates. */
  onChange(fn) {
    this.listeners.add(fn);
    return () => this.listeners.delete(fn);
  }
  notify() {
    for (const fn of this.listeners) {
      try {
        fn();
      } catch (e) {
        console.error("[page-status-bar] index listener threw:", e);
      }
    }
  }
  /** Schedule a one-time full rebuild on the next idle slot. Idempotent. */
  scheduleInitialBuild() {
    if (this.rebuildScheduled || this._ready)
      return;
    this.rebuildScheduled = true;
    const run = () => {
      try {
        this.rebuild();
        this._ready = true;
        this.notify();
      } finally {
        this.rebuildScheduled = false;
      }
    };
    const w = window;
    if (typeof w.requestIdleCallback === "function") {
      w.requestIdleCallback(run, { timeout: 2e3 });
    } else {
      setTimeout(run, 0);
    }
  }
  /** Full scan — O(files × keys). Called once. */
  rebuild() {
    this.incoming.clear();
    this.knownSources.clear();
    for (const file of this.app.vault.getMarkdownFiles()) {
      this.indexFile(file);
    }
  }
  /** Re-index one file (remove its old entries, scan its current frontmatter). */
  updateFile(file) {
    this.removeSource(file.path);
    this.indexFile(file);
    if (this._ready)
      this.notify();
  }
  /** Drop all edges originating from this source (used on delete + rename-out). */
  removeSource(sourcePath) {
    if (!this.knownSources.has(sourcePath))
      return;
    this.knownSources.delete(sourcePath);
    for (const [target, list] of this.incoming) {
      const filtered = list.filter((e) => e.sourcePath !== sourcePath);
      if (filtered.length === 0)
        this.incoming.delete(target);
      else if (filtered.length !== list.length)
        this.incoming.set(target, filtered);
    }
    if (this._ready)
      this.notify();
  }
  /** Handle rename: drop old, re-index under new path. */
  handleRename(file, oldPath) {
    this.removeSource(oldPath);
    this.indexFile(file);
    if (this._ready)
      this.notify();
  }
  /** Look up incoming edges by target file path. O(1). */
  incomingFor(targetPath) {
    return this.incoming.get(targetPath) ?? [];
  }
  // -- internal ----------------------------------------------------------
  indexFile(source) {
    const cache = this.app.metadataCache.getFileCache(source);
    const fm = cache?.frontmatter ?? {};
    if (Object.keys(fm).length === 0)
      return;
    this.knownSources.add(source.path);
    for (const key of Object.keys(fm)) {
      const v = fm[key];
      if (v == null)
        continue;
      for (const ref of asArray(v)) {
        const resolved = resolveLink(this.app, source, ref);
        if (resolved instanceof import_obsidian7.TFile) {
          this.add(resolved.path, source.path, key);
        }
      }
    }
  }
  add(targetPath, sourcePath, field) {
    let list = this.incoming.get(targetPath);
    if (!list) {
      list = [];
      this.incoming.set(targetPath, list);
    }
    list.push({ sourcePath, field });
  }
};

// src/main.ts
var LEGACY_STUB_RE = /```dataviewjs[\s\S]*?\bdv\.view\(\s*["']\{internals\}\/Classes\/_views\/any["']/;
var PageStatusBarPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.extensions = [];
    // Per-file legacy-stub presence cache. Cleared on metadata change.
    this.legacyStubCache = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.extensions.push(...projectExtensions);
    this.linkIndex = new LinkIndex(this.app);
    this.typeIndex = new TypeIndex(this.app);
    this.addSettingTab(new PageStatusBarSettingTab(this.app, this));
    setEditorViewBridge({
      app: this.app,
      getSettings: () => this.settings,
      getExtensions: () => this.extensions,
      getLinkIndex: () => this.linkIndex,
      getTypeIndex: () => this.typeIndex
    });
    this.registerMarkdownPostProcessor((el, ctx) => {
      if (this.settings.renderMode === "view-extension")
        return;
      this.handlePostProcess(el, ctx);
    });
    this.registerEditorExtension(statusBarViewExtension);
    this.addCommand({
      id: "page-status-bar-refresh",
      name: "Refresh status bar (this note)",
      callback: () => this.refreshActiveView()
    });
    this.addCommand({
      id: "page-status-bar-refresh-all",
      name: "Refresh status bars (all open notes)",
      callback: () => this.refreshAll()
    });
    this.applyBodyClasses();
  }
  onunload() {
    setEditorViewBridge(null);
    document.body.classList.remove("psb-hide-native-properties");
  }
  async loadSettings() {
    const raw = await this.loadData();
    this.settings = mergeSettings(DEFAULT_SETTINGS, raw ?? {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /** Toggle body class so styles.css can hide native properties. */
  applyBodyClasses() {
    document.body.classList.toggle(
      "psb-hide-native-properties",
      this.settings.hideNativeProperties
    );
  }
  refreshAll() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      const v = leaf.view;
      if (v instanceof import_obsidian8.MarkdownView && v.getMode() === "preview") {
        v.previewMode?.rerender?.(true);
      }
    });
    refreshAllEditorViews(this.app);
  }
  refreshActiveView() {
    const v = this.app.workspace.getActiveViewOfType(import_obsidian8.MarkdownView);
    if (!v)
      return;
    if (v.getMode() === "preview") {
      v.previewMode?.rerender?.(true);
    } else {
      refreshAllEditorViews(this.app);
    }
  }
  async handlePostProcess(el, ctx) {
    const sourcePath = ctx.sourcePath;
    if (!sourcePath)
      return;
    if (el.closest(".psb-root"))
      return;
    const file = this.app.vault.getAbstractFileByPath(sourcePath);
    if (!(file instanceof import_obsidian8.TFile))
      return;
    const fm = this.app.metadataCache.getFileCache(file)?.frontmatter ?? {};
    if (!shouldRenderFor(file, fm, this.settings, this.typeIndex))
      return;
    if (this.settings.deferToLegacyStub && await this.fileHasLegacyStub(file)) {
      return;
    }
    const previewRoot = el.closest(".markdown-preview-section");
    const parent = previewRoot ?? el.parentElement;
    if (el.querySelector(":scope > .psb-root"))
      return;
    if (el.previousElementSibling?.classList?.contains("psb-root"))
      return;
    if (parent?.querySelector(":scope > .psb-root"))
      return;
    const host = createDiv({ cls: "psb-root psb-reading" });
    const child = new RenderComponent(host);
    ctx.addChild(child);
    const component = child;
    const renderCtx = {
      app: this.app,
      file,
      frontmatter: fm,
      settings: this.settings,
      linkIndex: this.linkIndex,
      typeIndex: this.typeIndex
    };
    if (previewRoot) {
      previewRoot.insertBefore(host, previewRoot.firstChild);
    } else if (parent) {
      parent.insertBefore(host, el);
    } else {
      el.insertBefore(host, el.firstChild);
    }
    void renderStatusBar(host, renderCtx, component, this.extensions);
  }
  async fileHasLegacyStub(file) {
    const cached = this.legacyStubCache.get(file.path);
    if (cached !== void 0)
      return cached;
    try {
      const content = await this.app.vault.cachedRead(file);
      const has = LEGACY_STUB_RE.test(content);
      this.legacyStubCache.set(file.path, has);
      return has;
    } catch {
      return false;
    }
  }
};
var RenderComponent = class extends import_obsidian8.MarkdownRenderChild {
  constructor(containerEl) {
    super(containerEl);
  }
};
function mergeSettings(base, override) {
  return {
    ...base,
    ...override,
    sections: { ...base.sections, ...override.sections ?? {} },
    enabledExtensions: {
      ...base.enabledExtensions,
      ...override.enabledExtensions ?? {}
    },
    includeFolders: override.includeFolders ?? base.includeFolders,
    excludeFolders: override.excludeFolders ?? base.excludeFolders
  };
}
